<?php
/*
Part of pb-embedFlash v1.5
© Pascal Berkhahn, <novayuna@googlemail.com>, http://pascal-berkhahn.de
*/
if (isset($_GET['playlist']))
{
	$wpconfig = realpath('../../../../wp-config.php');
	if (!file_exists($wpconfig)) { exit('Could not find wp-config.php.'); }
	require_once($wpconfig);
	
	$mm = pb_embedFlash_mm_get_data(null, null, null, null);
	$id = (int) $_GET['playlist'];
	if (isset($mm['playlists'][$id]) && is_array($mm['playlists'][$id]['ids']))
	{
		header("content-type:text/xml;charset=utf-8");
		$playlist = '<?xml version="1.0" encoding="UTF-8"?><playlist version="1" xmlns="http://xspf.org/ns/0/">
	<title>Playlist</title>
	<info>Playlist generated by pb-embedFlash for the JW FLV Media Player</info>
	<annotation>versions: pb-embedFlash v'.PBEF_VERSION.', JW FLV Media Player v3.16</annotation>
		<trackList>';
		foreach ($mm['playlists'][$id]['ids'] as $k => $i)
		{
# fix for URLs with query data
			if(preg_match(pbef_buildpattern($pbef_hosters[$i][0],'url'),$mm['media'][$i]['url'])
				&& ($pos = strpos($mm['media'][$i]['url'], '&'))) // ? -> %3F // = -> %3A // & -> %26
			{
				$url = ($pos ? substr($mm['media'][$i]['url'], 0, $pos) : $mm['media'][$i]['url']);
			}
			$playlist .= '<track><location><![CDATA['.($url ? $url : $mm['media'][$i]['url']).']]></location>';
# /fix			$playlist .= '<track><location><![CDATA['.$mm['media'][$i]['url'].']]></location>';
			$playlist .= '<identifier><![CDATA['.$k.']]></identifier>';
			if (!empty($mm['media'][$i]['title'])) 		{ $playlist .= '<title><![CDATA['.$mm['media'][$i]['title'].']]></title>'; }
			if (!empty($mm['media'][$i]['album'])) 		{ $playlist .= '<album><![CDATA['.$mm['media'][$i]['album'].']]></album>'; }
			if (!empty($mm['media'][$i]['image'])) 		{ $playlist .= '<image><![CDATA['.$mm['media'][$i]['image'].']]></image>'; }
			if (!empty($mm['media'][$i]['link'])) 		{ $playlist .= '<info><![CDATA['.$mm['media'][$i]['link'].']]></info>'; }
			if (!empty($mm['media'][$i]['type'])) 		{ $playlist .= '<meta rel="type"><![CDATA['.$mm['media'][$i]['type'].']]></meta>'; }
			if (!empty($mm['media'][$i]['captions'])) 	{ $playlist .= '<meta rel="captions"><![CDATA['.$mm['media'][$i]['captions'].']]></meta>'; }
			if (!empty($mm['media'][$i]['audio'])) 		{ $playlist .= '<meta rel="audio"><![CDATA['.$mm['media'][$i]['audio'].']]></meta>'; }
			if (!empty($mm['media'][$i]['author'])) 	{ $playlist .= '<creator><![CDATA['.$mm['media'][$i]['author'].']]></creator>'; }
			$playlist .= '</track>';
		}
	$playlist .= '</trackList></playlist>';
	}
	exit($playlist);
} elseif (!function_exists('get_option')) { echo "Please don't load this file directly."; exit; }
$mm = pb_embedFlash_mm_get_data($_GET['orderby'], $_GET['order'], (int) $_GET['paged'], 15);
$count = pbef_options('mm');
wp_print_scripts(array('sack'));
?>
<script type="text/javascript" src="<?php echo PBEF_SITEPATH?>/js/mediamanager.js"></script>
<script type="text/javascript">
function pb_embedFlash_ajax_mm(mode, id, url, title, image, author, type, link, album, captions, audio, attributes, mid, orderby, order)
{
	var pbef_sack = new sack('<?php bloginfo('wpurl'); ?>/wp-admin/admin-ajax.php');

	pbef_sack.execute = 1;
	pbef_sack.method = 'POST';
	pbef_sack.setVar('action', 'pbefmediamanager');
	pbef_sack.setVar('mode', mode);
	pbef_sack.setVar('id', id);
	pbef_sack.setVar('url', url);
	pbef_sack.setVar('title', title);
	pbef_sack.setVar('image', image);
	pbef_sack.setVar('album', album);
	pbef_sack.setVar('link', link);
	pbef_sack.setVar('type', type);
	pbef_sack.setVar('captions', captions);
	pbef_sack.setVar('audio', audio);
	pbef_sack.setVar('author', author);
	pbef_sack.setVar('attributes', attributes);
	pbef_sack.setVar('mid', mid);
	pbef_sack.setVar('orderby', orderby);
	pbef_sack.setVar('order', order);
	pbef_sack.setVar('page', <?php echo (is_numeric($_GET['paged']) ? (int) $_GET['paged'] : 1); ?>);
	pbef_sack.setVar('limit', 15);
	pbef_sack.encVar('cookie', document.cookie, false);
	pbef_sack.onError = function() { alert('Ajax error in pb-embedFlash') };
	pbef_sack.runAJAX();

	return true;
}
</script>
<input type="hidden" id="pbef_sitepath" value="<?php echo PBEF_SITEPATH; ?>" />
<?php if ($_GET['mediamanager'] == 'media' || empty($_GET['mediamanager'])) : ?>
<div style="float: right; text-align: right; padding-bottom: 10px;">
	&raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>&amp;mediamanager=media" style="color: #D54E21"><?php _e('Manage media', 'pb-embedflash'); ?></a></strong>
	&nbsp;|&nbsp; &raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>&amp;mediamanager=playlists"><?php _e('Manage playlists', 'pb-embedflash'); ?></a></strong>
	&nbsp;|&nbsp; &raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>"><?php _e('Settings', 'pb-embedflash'); ?></a></strong>
</div>
<form accept-charset="utf-8" action="<?php echo $_SERVER['REQUEST_URI']; ?>" name="pbef_mm" method="get">
<?php
	parse_str($_SERVER['QUERY_STRING'], $queries);
	if (is_array($queries)) { foreach ($queries as $k => $v) {
		if ($k != 'paged') { echo '<input type="hidden" name="'.$k.'" value="'.$v.'" />'; }
	} } 
?>
	<div class="tablenav">
		<div style="float: left;">
			<select name="orderby" id="orderby" class='postform' >
				<option value="id"<?php if ($_GET['orderby'] == 'id') { echo ' selected="selected"'; } ?>><?php _e('ID', 'pb-embedflash'); ?></option>
				<option value="image"<?php if ($_GET['orderby'] == 'image') { echo ' selected="selected"'; } ?>><?php _e('Image', 'pb-embedflash'); ?></option>
				<option value="title"<?php if ($_GET['orderby'] == 'title') { echo ' selected="selected"'; } ?>><?php _e('Title', 'pb-embedflash'); ?></option>
				<option value="url"<?php if ($_GET['orderby'] == 'url') { echo ' selected="selected"'; } ?>><?php _e('URL', 'pb-embedflash'); ?></option>
				<option value="type"<?php if ($_GET['orderby'] == 'type') { echo ' selected="selected"'; } ?>><?php _e('Type', 'pb-embedflash'); ?></option>
				<option value="author"<?php if ($_GET['orderby'] == 'author') { echo ' selected="selected"'; } ?>><?php _e('Author', 'pb-embedflash'); ?></option>
				<option value="link"<?php if ($_GET['orderby'] == 'link') { echo ' selected="selected"'; } ?>><?php _e('Link', 'pb-embedflash'); ?></option>
				<option value="album"<?php if ($_GET['orderby'] == 'album') { echo ' selected="selected"'; } ?>><?php _e('Album', 'pb-embedflash'); ?></option>
				<option value="captions"<?php if ($_GET['orderby'] == 'captions') { echo ' selected="selected"'; } ?>><?php _e('Captions', 'pb-embedflash'); ?></option>
				<option value="audio"<?php if ($_GET['orderby'] == 'audio') { echo ' selected="selected"'; } ?>><?php _e('Audio', 'pb-embedflash'); ?></option>
			</select>
			<select name="order" id="order" class='postform' >
				<option value="ASC"<?php if ($_GET['order'] == 'ASC') { echo ' selected="selected"'; } ?>><?php _e('ascending', 'pb-embedflash'); ?></option>
				<option value="DESC"<?php if ($_GET['order'] == 'DESC') { echo ' selected="selected"'; } ?>><?php _e('descending', 'pb-embedflash'); ?></option>
			</select>
			<input type="submit" id="post-query-submit" value="<?php _e('Filter', 'pb-embedflash'); ?>" class="button-secondary" />
		</div>
	<?php 
	$page_links = paginate_links( array(
		'base' => add_query_arg( 'paged', '%#%' ),
		'format' => '',
		'total' => ceil(pb_embedFlash_mm_count_data('media') / 15),
		'current' => (is_numeric($_GET['paged']) ? $_GET['paged'] : 1)
	));
	if ($page_links) { echo '<div class="tablenav-pages">'.$page_links.'</div>'; }
	?>
	</div>
</form>
<br class="clear" />
<div id="media_table"><?php echo pb_embedFlash_generate_media_table($mm['media']); ?></div>
<p class="submit">
	<input type="button" value="<?php _e('Add medium', 'pb-embedflash'); ?> &raquo;" onclick="pb_embedFlash_mediamanager('media_add', '', '');" />
	<input type="button" value="<?php _e('Import medium', 'pb-embedflash'); ?> &raquo;" onclick="pb_embedFlash_mediamanager('media_import', '', '');" />
</p>
<div id="mediabox" class="mediabox">
	<input type="hidden" id="media-add-id" value="<?php echo ($count['count_media'] + 1); ?>" />
	<input type="hidden" id="media-edit-id" value="" /> <!-- if empty, medium will be added using media-add-id-->
	<input type="hidden" id="title-media-add" value="<?php _e('Add medium', 'pb-embedflash'); ?>" />
	<input type="hidden" id="title-media-edit" value="<?php _e('Edit medium', 'pb-embedflash'); ?>" />
	<fieldset>
		<h2 id="mediabox-title" style="padding-right: 0px;"></h2>
		<ul>
			<li><label for="media-url" title="<?php _e('Path to medium with heading http://', 'pb-embedflash'); ?>"><strong><?php _e('URL', 'pb-embedflash'); ?></strong> *</label><input type="text" id="media-url" value="" /></li>
			<li><label for="media-title" title="<?php _e('Title shown in playlists.', 'pb-embedflash'); ?>"><strong><?php _e('Title', 'pb-embedflash'); ?></strong> *</label><input type="text" id="media-title" value="" /></li>
			<li><label for="media-image" title="<?php _e('Preview image and playlist thumbnail.', 'pb-embedflash'); ?>"><strong><?php _e('Image', 'pb-embedflash'); ?></strong></label><input type="text" id="media-image" value="" /></li>
			<li><label for="media-author" title="<?php _e('Author will be displayed in playlists.', 'pb-embedflash'); ?>"><strong><?php _e('Author', 'pb-embedflash'); ?></strong></label><input type="text" id="media-author" value="" /></li>
			<li><label for="media-link" title="<?php _e('Used for linkfromdisplay flashvar and within playlists.', 'pb-embedflash'); ?>"><strong><?php _e('Link', 'pb-embedflash'); ?></strong></label><input type="text" id="media-link" value="" /></li>
			<li><label for="media-type" title="<?php _e('You can force a type if the player has problems auto-detecting it.', 'pb-embedflash'); ?>"><strong><?php _e('Type', 'pb-embedflash'); ?></strong></label>
				<select id="media-type"><option value="">&nbsp;</option>
					<?php global $pbef_jwmp_extensions; foreach ($pbef_jwmp_extensions as $ext) { ?> <option value="<?php echo $ext ?>"><?php echo $ext ?></option> <?php } ?>
				</select>
				<!-- <input type="text" id="media-add-type" value="" /> -->
			</li>
			<li><label for="media-captions" title="<?php _e('This is used for subtitles.', 'pb-embedflash'); ?>"><strong><?php _e('Captions', 'pb-embedflash'); ?></strong></label><input type="text" id="media-captions" value="" /></li>
			<li><label for="media-audio" title="<?php _e('This is used for adding an audio comment.', 'pb-embedflash'); ?>"><strong><?php _e('Audio', 'pb-embedflash'); ?></strong></label><input type="text" id="media-audio" value="" /></li>
			<li><label for="media-album" title="<?php _e("Set to 'commercial' to prevent the file from being skipped.", 'pb-embedflash'); ?>"><strong><?php _e('Album', 'pb-embedflash'); ?></strong></label><input type="text" id="media-album" value="" /></li>
			<li><label for="media-attributes" title="<?php _e('The attributes like width, height, flashvars, etc.', 'pb-embedflash'); ?>"><strong><?php _e('Attributes', 'pb-embedflash'); ?></strong></label><input type="text" id="media-attributes" value="" /></li>
		</ul>
		<div style="text-align:right;">
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('media_submit', '', '');" value="Save &raquo;" />
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('clear_media', '', '');" value="Close" />
		</div>
	</fieldset>
</div>
<div id="mediaimport" class="mediabox">
<?php $importitems = pb_embedFlash_mm_import_from_wp(); ?>
	<fieldset>
		<h2 id="mediaimport-title" style="padding-right: 0px;"><?php _e('Import medium', 'pb-embedflash'); ?></h2>
		<ul>
			<li><label for="media-import-items" title="<?php _e('Select the medium to import from the WordPress database', 'pb-embedflash'); ?>"><strong><?php _e('Attachments', 'pb-embedflash'); ?></strong></label>
				<select id="media-import-items">
					<?php foreach ($importitems as $i) { ?> <option value="<?php echo $i['ID']; ?>"><?php echo $i['post_title']; ?></option> <?php } ?>
				</select>
			</li>
		</ul>
		<div style="text-align:right;">
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('media_import_submit', '', '');" value="Import &raquo;" />
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('clear_import', '', '');" value="Close" />
		</div>
	</fieldset>
</div>

<?php elseif ($_GET['mediamanager'] == 'playlists') : ?>
<div style="float: right; text-align: right; padding-bottom: 10px;">
	&raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>&amp;mediamanager=media"><?php _e('Manage media', 'pb-embedflash'); ?></a></strong>
	&nbsp;|&nbsp; &raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>&amp;mediamanager=playlists" style="color: #D54E21"><?php _e('Manage playlists', 'pb-embedflash'); ?></a></strong>
	&nbsp;|&nbsp; &raquo; <strong><a href="<?php echo PBEF_ADMINPATH; ?>"><?php _e('Settings', 'pb-embedflash'); ?></a></strong>
</div>
<form accept-charset="utf-8" action="<?php echo $_SERVER['REQUEST_URI']; ?>" name="pbef_mm" method="get">
<?php
	parse_str($_SERVER['QUERY_STRING'], $queries);
	if (is_array($queries)) { foreach ($queries as $k => $v) {
		echo '<input type="hidden" name="'.$k.'" value="'.$v.'" />';
	} } 
?>
<div class="tablenav">
	<div style="float: left;">
		<select name="orderby" id="orderby" class='postform' >
			<option value="id"<?php if ($_GET['orderby'] == 'id') { echo ' selected="selected"'; } ?>><?php _e('ID', 'pb-embedflash'); ?></option>
			<option value="title"<?php if ($_GET['orderby'] == 'title') { echo ' selected="selected"'; } ?>><?php _e('Title', 'pb-embedflash'); ?></option>
			<option value="attributes"<?php if ($_GET['orderby'] == 'attributes') { echo ' selected="selected"'; } ?>><?php _e('Attributes', 'pb-embedflash'); ?></option>
		</select>
		<select name="order" id="order" class='postform' >
			<option value="ASC"<?php if ($_GET['order'] == 'ASC') { echo ' selected="selected"'; } ?>><?php _e('ascending', 'pb-embedflash'); ?></option>
			<option value="DESC"<?php if ($_GET['order'] == 'DESC') { echo ' selected="selected"'; } ?>><?php _e('descending', 'pb-embedflash'); ?></option>
		</select>
		<input type="submit" id="post-query-submit" value="<?php _e('Filter', 'pb-embedflash'); ?>" class="button-secondary" />
	</div>
	<?php 
	$page_links = paginate_links( array(
		'base' => add_query_arg( 'paged', '%#%' ),
		'format' => '',
		'total' => ceil(pb_embedFlash_mm_count_data('playlists') / 15),
		'current' => (is_numeric($_GET['paged']) ? $_GET['paged'] : 1)
	));
	if ($page_links) { echo '<div class="tablenav-pages">'.$page_links.'</div>'; }
	?>
</div>
</form>
<br class="clear" />
<div id="playlists_table"><?php echo pb_embedFlash_generate_playlists_table($mm); ?></div>
<br class="clear" />
<table id="media_available" class="widefat">
	<thead>
		<tr>
			<!-- <th scope="col" class="check-column"><input type="checkbox" onclick="checkAll(document.getElementById('posts-filter'));" /></th> -->
			<th scope="col"><?php _e('ID', 'pb-embedflash'); ?></th>
			<th scope="col"><?php _e('Title', 'pb-embedflash'); ?></th>
			<th scope="col"><?php _e('Add to playlist', 'pb-embedflash'); ?></th>
		</tr>
	</thead>
	<tbody id="playlists-list" class="list:post">
		<tr id="nomedia" style="text-align: center; display: none"><td colspan="3"><em><?php _e('No media', 'pb-embedflash'); ?></em></td></tr>
	<?php 
		$get = pb_embedFlash_mm_get_data('id', 'ASC', null, null);
		if (count($get['media'])) { foreach ($get['media'] as $id => $m) { ?>
		<tr id="media-<?php echo $id; ?>" class="alternate" valign="top">
			<!-- <th scope="row" class="check-column"><input type="checkbox" name="delete[]" value="<?php echo $id; ?>" /></th> -->
			<td><?php echo $id; ?></td>
			<td><strong id="media_items-<?php echo $id; ?>"><?php echo $m['title']; ?></strong></td>
			<td>
				<select id="media_items-<?php echo $id; ?>-select">
		<?php if (count($mm['playlists'])) { foreach ($mm['playlists'] as $i => $p) { ?>
					<option id="m-<?php echo $id; ?>_p-<?php echo $i; ?>" value="<?php echo $i; ?>"><?php echo $p['title']; ?></option>
		<?php } } else { ?>
					<option id="m-<?php echo $id; ?>_p-0" value="0"><?php _e('No playlists', 'pb-embedflash'); ?></option>
		<?php } ?>
				</select>
				<input type="button" id="media_items-<?php echo $id; ?>-button" class="button delete" onclick="pb_embedFlash_mediamanager('media_items_add', '<?php echo $id; ?>');" value="&raquo;"<?php if (count($mm['playlists']) == 0) { echo ' disabled="disabled"'; } ?> />
			</td>
		</tr>		
	<?php } } else { ?>
		<tr id="nomedia" class="alternate" valign="top">
			<!-- <th scope="row" class="check-column"><input type="checkbox" name="delete[]" value="<?php echo $id; ?>" /></th> -->
			<td colspan="3" style="text-align: center;"><em><?php _e('No media', 'pb-embedflash'); ?></em></td>
		</tr>
	<?php }?>
	</tbody>
</table>
<p class="submit"><input type="button" value="<?php _e('Add playlist', 'pb-embedflash'); ?> &raquo;" onclick=" pb_embedFlash_mediamanager('playlists_add', '', '');" /></p>
<div id="playlistsbox" class="mediabox">
	<input type="hidden" id="playlists-add-id" value="<?php echo ($count['count_playlists'] + 1); ?>" />
	<input type="hidden" id="playlists-edit-id" value="" />
	<input type="hidden" id="title-playlists-add" value="<?php _e('Add playlist', 'pb-embedflash'); ?>" />
	<input type="hidden" id="title-playlists-edit" value="<?php _e('Edit playlist', 'pb-embedflash'); ?>" />
	<fieldset>
		<h2 id="playlistsbox-title" style="padding-right: 0px;"></h2>
		<ul>
			<li><label for="playlists-title" title="<?php _e('The title is just used internally', 'pb-embedflash'); ?>"><strong><?php _e('Title', 'pb-embedflash'); ?></strong></label><input type="text" id="playlists-title" value="" /></li>
			<li><label for="playlists-attributes" title="<?php _e('The attributes like width, height, flashvars, etc.', 'pb-embedflash'); ?>"><strong><?php _e('Attributes', 'pb-embedflash'); ?></strong></label><input type="text" id="playlists-attributes" value="" /></li>
		</ul>
		<div style="text-align:right;">
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('playlists_submit', '', '');" value="Save &raquo;" />
			<input type="button" class="button" onclick="pb_embedFlash_mediamanager('clear_playlists', '', '');" value="Close" />
		</div>
	</fieldset>
</div>
<?php endif; ?>